apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: team-a-demo
  labels:
    app: client
    team: team-a
spec:
  nodeSelector:
    role: team-a
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "team-a"
      effect: "NoSchedule"
  containers:
    - name: client
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
        limits:
          memory: "32Mi"
          cpu: "50m"
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: team-b-demo
  labels:
    app: client
    team: team-b
spec:
  nodeSelector:
    role: team-b
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "team-b"
      effect: "NoSchedule"
  containers:
    - name: client
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
        limits:
          memory: "32Mi"
          cpu: "50m"
