apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
  namespace: team-a-demo
  labels:
    app: team-a-app
    team: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-app
  template:
    metadata:
      labels:
        app: team-a-app
        team: team-a
      annotations: {}
    spec:
      serviceAccountName: team-app
      nodeSelector:
        role: team-a
      tolerations:
        - key: "team"
          operator: "Equal"
          value: "team-a"
          effect: "NoSchedule"
      containers:
        - name: app
          image: tenant-app:v1
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
          env:
            - name: TEAM_NAME
              value: "team-a"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-gateway.platform-observability.svc.cluster.local:4317"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: team-a-svc
  namespace: team-a-demo
  labels:
    app: team-a-app
    team: team-a
spec:
  selector:
    app: team-a-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP