apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-gateway-config
  namespace: platform-observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
      resource:
        attributes:
          - key: platform
            value: kube-tenant-lab
            action: insert

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug]