apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-app
  namespace: team-a-demo
  labels:
    team: team-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-app
  namespace: team-b-demo
  labels:
    team: team-b
